using Phantasma.Mathematics;

namespace Phantasma.Cryptography.Ring
{
    public struct RingKeyPair
    {
        public readonly BigInteger PrivateKey;
        public readonly BigInteger PublicKey;

        public RingKeyPair(BigInteger privateKey, BigInteger publicKey)
        {
            this.PrivateKey = privateKey;
            this.PublicKey = publicKey;
        }
    }

    public interface ILinkableSignature
    {
        /// <summary>
        /// Checks whether two signatures were generated by the same signer
        /// </summary>
        bool IsLinked(ILinkableSignature other);
    }
}
