using Phantasma.Numerics;

namespace Phantasma.Cryptography.Ring
{
    public struct RingKeyPair
    {
        public readonly LargeInteger PrivateKey;
        public readonly LargeInteger PublicKey;

        public RingKeyPair(LargeInteger privateKey, LargeInteger publicKey)
        {
            this.PrivateKey = privateKey;
            this.PublicKey = publicKey;
        }
    }

    public interface ILinkableSignature
    {
        /// <summary>
        /// Checks whether two signatures were generated by the same signer
        /// </summary>
        bool IsLinked(ILinkableSignature other);
    }
}
